### ISSUE TITLE
Time Axis recomputeTickMarks throws exception on empty dataset 

### ISSUE THREAD

**Issue by tanrikut** [GSI-CS-CO/chart-fx#313]
I have an time axis with empty dataset. When I call recomputeTickMarks it throws following:

		xyChart.getXAxis().set("Time");
		xyChart.getXAxis().setTimeAxis(true);

		((DefaultNumericAxis) xyChart.getXAxis()).setAutoRangePadding(0.1);
		((DefaultNumericAxis) xyChart.getXAxis()).setAutoRangeRounding(false);

Caused by: java.time.DateTimeException: Invalid value for NanoOfSecond (valid values 0 - 999999999): 2147483647
	at java.base/java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
	at java.base/java.time.temporal.ChronoField.checkValidValue(ChronoField.java:717)
	at java.base/java.time.LocalDateTime.ofEpochSecond(LocalDateTime.java:418)
	at de.gsi.chart.axes.spi.format.DefaultTimeFormatter.formatHighResString(DefaultTimeFormatter.java:60)
	at de.gsi.chart.axes.spi.format.DefaultTimeFormatter.getTimeString(DefaultTimeFormatter.java:77)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1003)
	at de.gsi.chart.axes.spi.format.DefaultTimeFormatter.toString(DefaultTimeFormatter.java:134)
	at de.gsi.chart.axes.spi.AbstractAxis.getTickMarkLabel(AbstractAxis.java:339)
	at de.gsi.chart.axes.spi.AbstractAxis.lambda$computeTickMarks$9(AbstractAxis.java:685)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4411)
	at de.gsi.chart.axes.spi.AbstractAxis.computeTickMarks(AbstractAxis.java:683)
	at de.gsi.chart.axes.spi.AbstractAxis.recomputeTickMarks(AbstractAxis.java:1388)
	at de.gsi.chart.axes.spi.AbstractAxis.recomputeTickMarks(AbstractAxis.java:428)

**Comment by RalphSteinhagen** [comment]
Hi @tanrikut! I tried to reproduce your issue, however, without success (see commit). 

The stack trace you sent seems to point to a closing bracket: 
https://github.com/GSI-CS-CO/chart-fx/blob/dee77c1009f70d55cf51b6f8fab0f2bcf072171f/chartfx-chart/src/main/java/de/gsi/chart/axes/spi/AbstractAxis.java#L422-L430

Have you tested this against master? 

Could you perhaps provide an MVP that reproduces your observations? You may extend the test and propose a fix if you find the culprit.

**Comment by tanrikut** [comment]
Hi @RalphSteinhagen ,

Sorry for inconvience, I tested with 11.2.2 and it works without a problem.

**Comment by RalphSteinhagen** [comment]
@tanrikut no worries. Glad that it worked out for you as well! :+1:
